### ISSUE TITLE
Huge icons when searching for podcast

### ISSUE THREAD

**Issue by sparevermicelli** [chhoumann/PodNotes#27]
Hi, 

not sure if problem on my side as in the screenshots from you it looks different, but the icons I see when I am searching for a podcast are huge :)
![image](https://user-images.githubusercontent.com/67918791/186844407-14567fc7-26b2-4ad6-b012-911d7b6397f0.png)

**Comment by GitMurf** [comment]
Yes I noticed the same thing. I am using default Obsidian theme and on Windows.

**Comment by chhoumann** [comment]
Confirmed fixed — closing.

**Root cause (2.2.x era):** each result rendered its artwork as `<img style="width: 100%;">` inside a grid cell with no height/size constraint, so cover art filled the full column width and appeared huge.

**Fix:** the settings podcast view was redesigned in `c688e3e` ("redesign podcast view in settings"), released in **2.13.0**, which replaced the unconstrained image with a fixed-size thumbnail.

**Verified on current `master` (2.16.0):** in `src/ui/settings/PodcastResultCard.svelte` the artwork lives in a fixed `4rem × 4rem` container with `overflow: hidden`, and the image uses `object-fit: cover`:

```css
.podcast-artwork-container { width: 4rem; height: 4rem; flex-shrink: 0; overflow: hidden; }
.podcast-artwork { width: 100%; height: 100%; object-fit: cover; }
```

Driving the real Obsidian app and inspecting a rendered result card, the artwork measures exactly **64×64px** (`object-fit: cover`) regardless of theme/platform — no longer huge. The `semantic-release` bot already flagged this resolved in 2.13.0; closing now that it's verified against current `master`.
